### ISSUE TITLE
Is deface really used by this plugin?

### ISSUE THREAD

**Issue by mmoll** [theforeman/ovirt_provision_plugin#10]
If not, it should get removed.

**Comment by bronhaim** [comment]
seems like its not. I'll remove that and verify
the engine.rb code was probably copied from another plugin

**Comment by mmoll** [comment]
@bronhaim any update here? :)

**Comment by bronhaim** [comment]
Hi ;) Thanks for raising again! Checked that, and it looks redundant - will remove it as part of my comeback now

**Comment by masayag** [comment]
Closed by https://github.com/theforeman/ovirt_provision_plugin/pull/21
