### ISSUE TITLE
Push tags to github

### ISSUE THREAD

**Issue by ekohl** [theforeman/ovirt_provision_plugin#13]
Currently there are releases on rubygems but the tags weren't pushed to github. It'd be useful to have those.

**Comment by masayag** [comment]
@ekohl could you provide more info about tags management and what information should be included ? (only git tags?) or some other metadata ?

**Comment by ekohl** [comment]
@masayag just git tags is sufficient.

**Comment by masayag** [comment]
Tags added for v2.0.0 - https://github.com/theforeman/ovirt_provision_plugin/releases/tag/v2.0.0
